jdbc:
  url: jdbc:mysql://localhost:3306/AGV_WTools?zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Taipei&characterEncoding=utf-8&useUnicode=true
  username: root
  password: 12345678

agvControl:
#  url: http://192.168.0.100:20100
  url: http://10.11.33.232:20100
#  url: http://localhost:20101

agv:
  low_battery: 70  # AGV電量低於多少時，派遣回待命點
  low_battery_duration: 60  # AGV電量低於多少時，派遣回待命點

caller:
  offline_duration: 20

http:
  max_retry: 3